# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js 16 base image
FROM node:16 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . .

# Build the project
RUN npm run build

# Use a lightweight Node.js image for the production environment
FROM node:16-slim AS production

# Set the working directory inside the container
WORKDIR /app

# Copy built files from the build stage
COPY --from=build /app/build /app/build

# Copy node_modules from the build stage
COPY --from=build /app/node_modules /app/node_modules

# Expose any necessary ports
EXPOSE 6333

# Environment variables
ENV QDRANT_URL=http://localhost:6333
ENV EMBEDDING_PROVIDER=ollama
ENV OLLAMA_URL=http://localhost:11434

# Run the application
CMD ["node", "build/index.js"]
